server:
  servlet:
    context-path: "/api"

spring:
  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
  jpa:
    hibernate:
      ddl-auto: update

---

spring:
  config:
    import:
      - classpath:test.yml
    activate:
      on-profile: test, local-test

---

spring:
  config:
    import:
      - classpath:prod.yml
    activate:
      on-profile: prod, local-prod
