server:
  servlet:
    context-path: "/api"

spring:
  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}

---

spring:
  config:
    activate:
      on-profile: test, local-test
  jpa:
    hibernate:
      ddl-auto: update

---

spring:
  config:
    activate:
      on-profile: prod, local-prod
  jpa:
    hibernate:
      ddl-auto: validate