name: Deploy Admin and User to S3

on:
  workflow_dispatch:

jobs:
  build-root:
    name: Build Root Project
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache Node.js dependencies
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: ./react/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('./react/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies for Root Project
        working-directory: ./react
        run: npm install

  build-and-deploy-admin:
    name: Build and Deploy Admin
    runs-on: ubuntu-latest
    needs: build-root

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Restore Node.js dependencies cache
        uses: actions/cache@v3
        with:
          path: ./react/node_modules
          key: ${{ needs.build-root.outputs.cache-node-modules-key }}

      - name: Build the Admin project
        working-directory: ./react/app/admin
        run: npm run build:production

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Admin to S3
        run: |
          aws s3 sync ./react/app/admin/dist s3://${{ secrets.S3_BUCKET_NAME }}/admin --acl public-read --delete

  build-and-deploy-user:
    name: Build and Deploy User
    runs-on: ubuntu-latest
    needs: build-root

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Restore Node.js dependencies cache
        uses: actions/cache@v3
        with:
          path: ./react/node_modules
          key: ${{ needs.build-root.outputs.cache-node-modules-key }}

      - name: Build the User project
        working-directory: ./react/app/user
        run: npm run build:production

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload User to S3
        run: |
          aws s3 sync ./react/app/user/dist s3://${{ secrets.S3_BUCKET_NAME }}/user --acl public-read --delete
