name: Deploy Admin and User to S3

on:
  workflow_dispatch:  # 수동으로 실행할 수 있도록 설정

jobs:
  build-root:
    name: Build Root Project
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Node.js 버전

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: ./react/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('./react/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies for Root Project
        working-directory: ./react  # 루트 package.json이 있는 디렉토리
        run: npm install  # 의존성 설치

      - name: Save node_modules cache
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        uses: actions/cache@v2
        with:
          path: ./react/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('./react/package-lock.json') }}
        
  build-and-deploy-admin:
    name: Build and Deploy Admin
    runs-on: ubuntu-latest
    needs: build-root

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Node.js 버전을 적절히 설정

      - name: Restore node_modules cache
        uses: actions/cache@v2
        with:
          path: ./react/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('./react/package-lock.json') }}

      - name: Build the Admin project
        working-directory: ./react/app/admin  # Admin 프로젝트의 경로
        env:
          PATH: ./react/node_modules/.bin:${{ env.PATH }} # Ensure the root's node_modules/.bin is in the PATH
        run: npm run build:production

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Admin to S3
        run: |
          aws s3 sync ./react/app/admin/dist s3://${{ secrets.S3_BUCKET_NAME }}/admin --acl public-read --delete

  build-and-deploy-user:
    name: Build and Deploy User
    runs-on: ubuntu-latest
    needs: build-root

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Node.js 버전을 적절히 설정

      - name: Build the User project
        working-directory: ./react/app/user  # User 프로젝트의 경로
        run: npm run build:production

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload User to S3
        run: |
          aws s3 sync ./react/app/user/dist s3://${{ secrets.S3_BUCKET_NAME }}/user --acl public-read --delete
